// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRizEJB-5tdlQoraPcShRPwRo_-sLlpA',
    appId: '1:118208404931:web:7768250e403100c06bb176',
    messagingSenderId: '118208404931',
    projectId: 'socialtrails-f89bc',
    authDomain: 'socialtrails-f89bc.firebaseapp.com',
    databaseURL: 'https://socialtrails-f89bc-default-rtdb.firebaseio.com',
    storageBucket: 'socialtrails-f89bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxFOjhB6HIIxBBLJ957uWPInB92bqUE9w',
    appId: '1:118208404931:android:84720f138188a04e6bb176',
    messagingSenderId: '118208404931',
    projectId: 'socialtrails-f89bc',
    databaseURL: 'https://socialtrails-f89bc-default-rtdb.firebaseio.com',
    storageBucket: 'socialtrails-f89bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvskUgEW00YHLKiFJ_WziOn665rE8_oNg',
    appId: '1:118208404931:ios:07aa2a0e9235dca66bb176',
    messagingSenderId: '118208404931',
    projectId: 'socialtrails-f89bc',
    databaseURL: 'https://socialtrails-f89bc-default-rtdb.firebaseio.com',
    storageBucket: 'socialtrails-f89bc.appspot.com',
    iosBundleId: 'com.example.socialtrailsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvskUgEW00YHLKiFJ_WziOn665rE8_oNg',
    appId: '1:118208404931:ios:07aa2a0e9235dca66bb176',
    messagingSenderId: '118208404931',
    projectId: 'socialtrails-f89bc',
    databaseURL: 'https://socialtrails-f89bc-default-rtdb.firebaseio.com',
    storageBucket: 'socialtrails-f89bc.appspot.com',
    iosBundleId: 'com.example.socialtrailsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyRizEJB-5tdlQoraPcShRPwRo_-sLlpA',
    appId: '1:118208404931:web:55257ed81799cc4e6bb176',
    messagingSenderId: '118208404931',
    projectId: 'socialtrails-f89bc',
    authDomain: 'socialtrails-f89bc.firebaseapp.com',
    databaseURL: 'https://socialtrails-f89bc-default-rtdb.firebaseio.com',
    storageBucket: 'socialtrails-f89bc.appspot.com',
  );
}
